# Generated by Django 5.1.7 on 2025-03-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assignee',
        ),
    ]
